### ISSUE TITLE
The editor toolbar insertion of table issues.

### ISSUE THREAD

**Issue by jx-bamboo** [Daniele-rolli/Beaver-Notes#152]
Hi Daniele rolli,
Happy to update to 3.0.0
I insert a table and I can't find a button to add a row or column.
But when I reopened it and clicked on the form again to prepare for input, a new line of tools for adding a row or a column appeared. And it cannot disappear, it always follows the mouse pointer. I think it's a little bit fluid.
When I click the delete button on the new toolbar, the entire table is gone, oh my god.
I think it would be more convenient to add a small button to the border of the last row or column.

**Comment by Daniele-rolli** [comment]
Thank you for your feedback. The floating toolbar should disappear while typing to avoid interference. I'll explore options for adding a button to delete the table rather than having it in the floating toolbar. Additionally, we could consider removing the button altogether, as the table can be deleted using the backspace key.

**Comment by jx-bamboo** [comment]
I'm sorry for forgetting to provide my platform for yesterday's question, formatting is a good practice.

System: ubuntu23.04.
Version: 3.0.0.

It should be updated to 24.04 as soon as possible next month.
