### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by jonocodes** [Daniele-rolli/Beaver-Notes#154]
Thanks for packaging for so many platforms... but how about a flatpack on flathub? Its a somewhat universal package manager/repository.

For example I am running NixOS, where it can sometimes be difficult to run an AppImage. I found out about this project since someone filed a nix packaging request: https://github.com/NixOS/nixpkgs/issues/295385

But flatpack is a cross distro solution that includes updates and discoverablilty.

**Comment by Daniele-rolli** [comment]
Thanks for your input! I'm pleased to hear that you find the packaging helpful. Making Beaver Notes available on Flathub sounds like a feasible idea, and it's a great way to ensure accessibility to even more people. I'll definitely explore this option further. Thanks again for your suggestion!

**Comment by Daniele-rolli** [comment]
A couple of days ago, I opened this pull request to submit Beaver to Flathub (https://github.com/flathub/flathub/pull/5158). As of now, the only thing we can do is wait until the request is merged. Thanks again for your input.

**Comment by Daniele-rolli** [comment]
We could drop rpm and deb, but I don't see the need to do so. In the end, using Flatpak means simply changing a version number, which could be done with a workflow, so there's no issue with packaging a new release. I also believe that it would cause more harm than good, since we've already built the infrastructure to distribute our packages through rpm and deb, and most of our users rely on them. That said, let's hope we make it onto Flathub soon.

**Comment by Daniele-rolli** [comment]
I'm glad to report that Beaver is now available on [Flathub](https://flathub.org/apps/com.beavernotes.beavernotes)

**Comment by jonocodes** [comment]
Great. I tried it and it works. I'm using NixOS.
