### ISSUE TITLE
AppImage Questions

### ISSUE THREAD

**Issue by in4matix** [Daniele-rolli/Beaver-Notes#160]
Thank you for this app. Busy trying the Appimage version on Ubuntu 22.04. App seems to be working very well. Very responsive. I just have two questions:
1. App does not seem to support persistent window sizing between launches and exits?
2. How to change accent color (orange color) ?

**Comment by Daniele-rolli** [comment]
Hey, thanks for taking the time to ask these questions. Unfortunately, support for persistent window sizing is not available due to electron limitations. Additionally, the accent color is actually a part of the application, and there's no way to change it since it's written this way. I hope my answers are not too disappointing, and you'll still enjoy Beaver as much as I do.

**Comment by Daniele-rolli** [comment]
I've done some googling and found out that a library called electron-window-state lets you store and restore the window sizing and position. I'll try to add it to the app. If everything works as planned, this might make it into the next version.

**Comment by Daniele-rolli** [comment]
Good news! Beaver will be able to retain and restore the size and position of a window, as per commit 9dc7b9c. Thanks again for your feedback.

**Comment by in4matix** [comment]
Awesome! Thanks!
