### ISSUE TITLE
Obscure Password Field 

### ISSUE THREAD

**Issue by eag75** [Daniele-rolli/Beaver-Notes#53]
Hello Daniele,

could you please build into the app that passwords are no longer displayed in plain text in the input fields? I think that would be a real benefit in terms of security.

I once searched the Internet for an example of how something like this could be implemented. But I'm not that experienced in Javascript, so I'll just link you to the article.

[https://www.peoray.dev/blog/display-password-form-input/](https://www.peoray.dev/blog/display-password-form-input/)

Best regards
Danny

**Comment by Daniele-rolli** [comment]
I'll look into options for displaying the password in a more secure way, rather than revealing its content. I appreciate the guides you've shared. However, they don't precisely match our case, as the app uses a different design to show the dialog. Nevertheless, I'm sure that it's just a matter of slightly adjusting the design.

**Comment by Daniele-rolli** [comment]
<img width="1062" alt="Screenshot 2024-01-02 at 10 10 10 PM" src="https://github.com/Daniele-rolli/Beaver-Notes/assets/67503004/2a703cc3-b640-435c-a6d7-fa2c2a6c8909">

I think this should do it. I've already implemented it for both locking notes and encrypting/decrypting data during export/import.

**Comment by eag75** [comment]
Looks good! 😁
