### ISSUE TITLE
Using Milkdown as Markdown Parser

### ISSUE THREAD

**Issue by Humorist2601** [Daniele-rolli/Beaver-Notes#57]
**Question or Assistance Request**

- [x] I have reviewed existing issues and discussions to find a solution to my question.
- [x] I have checked the documentation and relevant resources for answers.
- [x] This question is related to the project and within the scope of this repository.

**Description**
Have you considered using [Milkdown](https://milkdown.dev/) as the parser instead of Tiptap. I think it would be more suitable for this app.

**Comment by Daniele-rolli** [comment]
Thanks for the suggestion. I considered using Milkdown while developing the app; however, I chose Tiptap in the end, as I personally found it more modular and easier to develop with. I will consider Milkdown for future projects; however, as of now, I don't see the benefits of rewriting Beaver using Milkdown, since our stack is already tailored for Tiptap. That said, there are plans to allow exporting and importing code into and from Markdown and other formats.
