### ISSUE TITLE
Package Manager(s)

### ISSUE THREAD

**Issue by phoward38** [Daniele-rolli/Beaver-Notes#6]
Not a deal breaker, but just curious if you have plans of making it available on any package managers (e.g. `Homebrew`)? BTW, looking good so far!

**Comment by Daniele-rolli** [comment]
Update: Since this issue was opened, I've been working on implementing some package managers to make Beaver Notes more accessible and easier to install. The first package manager through which we've made Beaver Notes available is apt. You can check out [Beaver-notes-ppa](https://github.com/Daniele-rolli/Beaver-notes-ppa) for details. A version for Homebrew is also in the works; let's hope the cask will be accepted right away. As this issue is considered to be an enhancement, the conversation will be moved to the conversation section of this GitHub repository.
